Repository Dinn/git-workflow-exercise, pull requests merged in 2020-06, with the labels that each got.

#6 feature: test feature 추가
  newfile.js
Labels: C: 4h

#9 add : feature03.js
  Feature03.js
Labels: C: 4h, E:2, add

#17 feature : 콘솔 기능 구현!!
  Feature03.js
Labels: feature
